added unit tests for extractMetadata helper functions
owncloud/web-app-dicom-viewer pull request #38
Opened 2024-04-02 11:07 UTC by PrajwolAmatya

## Description
Added unit test for helper function in `extractMetadata.ts`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added

2024-04-04 09:32 UTC, saw-jan requested changes

2024-04-04 09:32 UTC, saw-jan commented on pnpm-lock.yaml
> -    version: 6.7.0
not expecting the change in lock file

2024-04-04 09:33 UTC, saw-jan commented on tests/unit/helper/extractMetadata.spec.ts
> +const imageData = {
```suggestion
const mockImageData = {
```

2024-04-05 04:16 UTC, Salipa-Gurung commented on tests/unit/helper/extractMetadata.spec.ts
> +      const dicomMetaData = await extractDicomMetadata(imageData, ['patientName'], 'en')
maybe we can add another test case where the tags has to be removed.

2024-04-11 06:05 UTC, koebel commented on tests/unit/helper/extractMetadata.spec.ts
> +      )
I think you need to test more inputs. In addition to a standard tag like "patientName" that just returns the value from meta data and empty/undefined value you need to add
- some tag with _formatDate like for example "patientBirthdate" which should return a date value that has been formatted nicely
- some tag with _formatTime like instanceCreationTime which should return a time value that has been formatted nicely
- some tag with _addSOPuids like SOP_ClassUID which should return the SOP class together with the description
You might also want to test what happend if someone passes an invalid tag into this function (I think it should return undefined)

2024-04-11 10:49 UTC, koebel commented on src/helper/extractMetadata.ts
> +  console.log(extractedData)
I guess this was just for "spying" on the values produced by this function :)

2024-04-11 10:49 UTC, koebel commented on src/helper/extractMetadata.ts
> +  console.log(date)
same as above...

2024-04-11 11:24 UTC, koebel commented on src/helper/extractMetadata.ts
> +  console.log(extractedData)
no probs

2024-04-11 11:25 UTC, koebel approved these changes
LGTM - however get some feedback from others in the team too before merging

2024-04-15 03:52 UTC, saw-jan approved these changes
LGTM

2024-04-15 04:11 UTC, merged